name: Update version

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  version:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pdm
        uses: pdm-project/setup-pdm@main
        with:
          python-version: "3.10"
          enable-pep582: true
        
      - name: Update pyproject.toml version
        run: |
          pdm install
          pdm plugin add pdm-version
          pdm version ${{ github.ref_name }}

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Update version
          committer_name: actions
          committer_email: actions@github.com

      - name: Delete tag and create a new one
        run: |
          git tag -d ${{ github.ref_name }}
          git tag ${{ github.ref_name }}
      
      - name: Push tag change
        uses: EndBug/add-and-commit@v9
        with:
          push: 'origin :refs/tags/${{ github.ref_name }}'
