name: Publish package

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  reusable:
    uses: la-catalog/github-actions/.github/workflows/python_publish.yml@main
    secrets:
      gh_token: ${{ secrets.gh_token }}